# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7d80e1551492ec1145a329161074abdaa57c610bbb718e7d143fa687f84d60a7b31e35d14e1838504d1edf38b39676cebd725ec44ad49bf6b73440eea38e61d

test:
  secret_key_base: 1e8bbbccc4c27d4afcb1dbb2a62b73d7c14eae15c3f1a1d930dad0c59db212f1cf58165f684b8c4f411e0753f812d09dd1d67841152d025380302a5fc8d55ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
